/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "labteste.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX_WORDS 1000
#define STR_SIZE 100 //STR_SIZE doesn't have to be a constant

result *
wordcount_100_svc(params *argp, struct svc_req *rqstp)
{
	printf("estou na server!\n");
	static result resultado;
	int temp;
	int i,j,k;
	int len, isUnique;

	resultado.object.object_val = (char **)malloc(100 * sizeof(char));
	char *word = (char *) malloc(50 * sizeof(char));
	for (temp = 0; temp < 100; temp++)
        *(resultado.object.object_val + temp) = (char *)malloc(50 * sizeof(char));
	FILE *fptr;
	/* Input file path */
	//printf("Enter file path: ");
	/* Try to open file */

	fptr = fopen(argp->arqName, "r");

	/* Exit if file not opened successfully */

	if (fptr == NULL)
	{
		printf("Unable to open file.\n");
		printf("Please check you have read previleges.\n");

		exit(EXIT_FAILURE);
	}

	for (k = 0; k < MAX_WORDS; k++)
	resultado.count[k] = 0;
	
	while (fscanf(fptr, "%s", word) != EOF)
	{
		// Convert word to lowercase
		// strlwr(word);

		// Remove last punctuation character
		len = strlen(word);
		if (ispunct(word[len - 1]))
			word[len - 1] = '\0';

		// Check if word exits in list of all distinct words
		isUnique = 1;
		for (k = 0; k < resultado.index && isUnique; k++)
		{
			if (strcmp(resultado.object.object_val[k], word) == 0)
				isUnique = 0;
		}

		// If word is unique then add it to distinct words list
		// and increment index. Otherwise increment occurrence
		// count of current word.
		if (isUnique)
		{
			strcpy(resultado.object.object_val[resultado.index], word);
			resultado.count[resultado.index]++;

			resultado.index++;
		}
		else
		{
			resultado.count[k - 1]++;
		}
	}
	//&(*mat[1])
	printf("P1:%s\n",&(*resultado.object.object_val[0]));
 
	return &(resultado);
}
