/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "labteste.h"
#include <string.h>
//char **readerArq(char nameArq[100],int count[1000],int index)

result wordcont(CLIENT *clnt, char arqName[100])
{
	int temp=0;
	params par;
	result *resultado;
	strcpy(par.arqName, arqName);

	/* Chama o stub cliente criado pelo rpcgen */
	resultado = wordcount_100(&par, clnt);

	if (resultado == NULL)
	{
		fprintf(stderr, "Problema na chamada RPC\n");
		exit(0);
	}
	//printf("passei aqui!\n");
	printf("P1:%s\n",&(**(resultado->object.object_val)));

	return (*resultado);
} /* fim função add local */


int
main (int argc, char *argv[])
{
	result resultado;
	CLIENT *clnt;
	char arqName[100];
	

	if (argc != 3)
	{
		fprintf(stderr, "Uso: %s hostname num1 num2\n", argv[0]);
		exit(0);
	}

	clnt = clnt_create(argv[1], PROG, VERSAO, "udp");
	/* Garantindo a criacao da ligacao com o remoto */
	if (clnt == (CLIENT *)NULL)
	{
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	/* Recupera os 2 operandos passados como argumento */
	strcpy(arqName, argv[2]);

	// printf("%s\n",arqName);

	resultado = wordcont(clnt,arqName);
	
	//printf("P1:%s\n",&(*(resultado.object.object_val[0])));
	

	return (0);
}
