/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "labteste.h"

bool_t
xdr_params (XDR *xdrs, params *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->arqName, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_words (XDR *xdrs, words *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_result (XDR *xdrs, result *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_array (xdrs, (char **)&objp->object.object_val, (u_int *) &objp->object.object_len, ~0,
			sizeof (words), (xdrproc_t) xdr_words))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (1 +  1000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->count, 1000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->index))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->count;
					i < 1000; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->index);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_array (xdrs, (char **)&objp->object.object_val, (u_int *) &objp->object.object_len, ~0,
			sizeof (words), (xdrproc_t) xdr_words))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (1 +  1000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->count, 1000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->index))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->count;
					i < 1000; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->index = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_array (xdrs, (char **)&objp->object.object_val, (u_int *) &objp->object.object_len, ~0,
		sizeof (words), (xdrproc_t) xdr_words))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->count, 1000,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->index))
		 return FALSE;
	return TRUE;
}
